name: sample
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_contacts: ^1.1.7+1
  flutter_map: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
